project:
  type: website
website:
  title: "Yu Cheng Hsu"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - text: Courses
        menu:
        - text: Scientific computing
          href: programming.qmd
        - text: Hybrid PBL Lectures
          href: hybridPBL.qmd
        - text: Quantitative analysis
          href: quant.qmd          
format:
  html:
    theme: lux
    
execute:
  freeze: auto