project:
  type: website

website:
  title: "Course Material Website"
  site-url: https://ychsu987.github.io
  description: "Bioinformaticist"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: courses.qmd
        text: Courses
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

