project:
  type: website
  output-dir: docs

website:
  title: "Course Material Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: courses.qmd
        text: Courses
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
