project:
  type: website
website:
  title: "Yu Cheng Hsu"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: courses.qmd
        text: Courses
      - text: Courses
        menu:
        - text: "BBMS1021 Introduction to AI and Biomedical Data Science" 
          href: bbms1021_course.qmd
        - text: Hybrid PBL Lectures
          href: hybridPBL.qmd
          
format:
  html:
    theme: litera
    css: styles.css
    
execute:
  freeze: auto