project:
  type: website
  resources:
    - "AILT9015/"
    - "assets/"
website:
  title: "Yu Cheng Hsu"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - text: Courses
        menu:
        - text: Common core
          href: cc.qmd       
        - text: Hybrid PBL Lectures
          href: hybridPBL.qmd
        - text: Quantitative analysis
          href: quant.qmd       
        - text: Course overview (Current Term + Archive)
          href: courses.qmd
        - text: Scientific computing
          href: programming.qmd
   
format:
  html:
    theme: litera
    
execute:
  freeze: auto