---
title: "Introduction to R"
subtitle: Data visualization in ggplot2
title-slide-attributes:
    data-background: /assets/images/ggplot2/background-1.png
    data-background-size:  40% 100%
    data-background-position: right
    data-background-opacity: "0.8"
author: Yu Cheng Hsu
format: 
  revealjs:
    theme: [default, ../../../assets/css/general_style.css]
    slide-number: true
    reference-location: margin
    chalkboard: true
    smaller: true
bibliography: ref.bib
lightbox: true
---

## Learning objectives

By the end of this session, you will

- Understand the basic grammar and layered structure of `ggplot2`
- Identify common graph components and choose an appropriate chart type
- Create simple plots using data, aesthetics, and geometric layers
- Interpret the main elements of a `ggplot2` figure

We **DO NOT** expect:

- Memorize functions in the `ggplot2`

## Preamble

**About Ray's part**

I am responsible for introducing commonly used libraries in R. So most of the time we will keep using functions that are predefined by others. 

Questions that Ray could **barely** give you an explanation better than AI/documentation:
  
- "What does this function do" -> Go to find the documentation `?FUNCTION_NAME` or ask AI
- "Why is this named XXXX()" -> The developer named it that way

Questions and competency you need to develop:

- "Why we need to do this?"
- Describe the task so AI can help you generate code
- Comprehend and relate to the code and make your own judgment


# Installing packages

{{< include /_content/modules/bdata/package.qmd >}}

# ggplot2

{{< include /_content/modules/bdata/ggplot2.qmd >}}

# File structure

{{< include /_content/modules/bdata/file.qmd >}}


## Bibliography notes

