## Variables

:::{.columns}

:::{.columm}
In python there two fundamental data type

- Numbers (Pure values)
- Strings (wrapped in quote marks "")

We can store these values using `=` in a `variable`

 - Can only contain A-z, 0-9, and _ 
 - Must start with letter
 - Case-sensitive

*Side notes*: numbers can be further categorized by their storage methods
:::

:::{.columm}
```{python}
#| echo: true
#| eval: true
#| 
# The '#' symbol is a comment. Python ignores it. We use it to leave notes.
# Let's store a short snippet of a target gene:
target_gene_1 = "ATGCGTAACGTTAGCGCC"
target_gene_2 = "CCGCGATTGCAATGCGTA"

gene_1_expr = 15
gene_2_expr = 20

# To see what is inside our variable, we use the print function:
print(target_gene_1)
print(gene_1_expr)
```
:::

:::

## Mathematical Operations


:::{.columns}

:::{.columm}

Python works exactly like a scientific calculator. The basic operators are: 

- addition (+)
- subtraction (-)
- multiplication (*)
- division (/)
- exponents (**)

*Side notes*: Do not skip multiplication signs as you do in math

:::

:::{.columm}
```{python}
#| echo: true
#| eval: true

# Simulating a PCR reaction
starting_templates = 5
pcr_cycles = 30

# The double asterisk (**) means "to the power of"
final_copies = starting_templates * (2 ** pcr_cycles)

print("Starting DNA templates:", starting_templates)
print("Final copies after 30 cycles:", final_copies)
```
:::

:::

## Functions


:::{.columns}

:::{.columm}

Function is a predefined set of code to make you perform specific task.

`function_name(input1, input_2, ...)`

For example `print()` is a function to print out the string and values
Here we introduce another function `len()` to inspect how long is the string
:::

:::{.columm}
```{python}
#| echo: true
#| eval: true

# Calculate the length of the target gene
seq_1_length = len(target_gene_1)
seq_2_length = len(target_gene_2)

# We can print text and variables together by separating them with a comma
print("Total base pairs (Seq 1):", seq_1_length)
print("Total base pairs (Seq 2):", seq_2_length)

```
:::

:::

## Methods

:::{.columns}

:::{.columm}

Variables that store text (Strings) have special actions they can perform, called methods. We can ask our DNA sequence to count specific motifs or bases using .count().

:::

:::{.columm}
```{python}
#| echo: true
#| eval: true

# Count the number of Adenine bases in our sequence from Step 1
a_count = target_gene_1.count("A")
print("Number of A bases:", a_count)

# Count a specific motif (e.g., a CpG site)
cpg_count = target_gene_1.count("CG")
print("Number of CpG sites:", cpg_count)
```
:::

:::

## Exercise: Calculating GC-Content


:::{.columns}

:::{.columm}

GC-content is crucial for determining the melting temperature of PCR primers (G-C base pairs form 3 hydrogen bonds, but A-T forms 2). Let's calculate it using basic Python math 

:::

:::{.columm}
```{python}
#| echo: true
#| eval: true

# Count the number of Adenine bases in our sequence from Step 1
a_count = target_gene_1.count("A")
print("Number of A bases:", a_count)

# Count a specific motif (e.g., a CpG site)
cpg_count = target_gene_1.count("CG")
print("Number of CpG sites:", cpg_count)
```
:::

:::

## Replacing strings: Simulating Transcription


:::{.columns}

:::{.columm}

When DNA is transcribed to mRNA, Thymine (T) is replaced by Uracil (U). We can simulate this biological process instantly with the `.replace()` method.

:::

:::{.columm}
```{python}
#| echo: true
#| eval: true

# Transcribe the DNA to RNA by replacing T with U
mrna_sequence = target_gene.replace("T", "U")

print("Original DNA:", target_gene)
print("Transcribed mRNA:", mrna_sequence)
```
:::

:::
