#!/usr/bin/env python3
"""Flatten lecture .qmd files for student distribution.

Source lectures on the website keep {{< include >}} shortcodes.
This script writes standalone copies next to the source:

  python scripts/flatten_qmd.py courses/2026/SBMS7202/introR.qmd --mode full
  python scripts/flatten_qmd.py courses/2026/SBMS7202/introR.qmd --mode worksheet
  python scripts/flatten_qmd.py courses/2026/SBMS7202/introR.qmd --mode both

Copies are written under _student/ so they are not published and do not
collide with lectures such as adt-model-full.qmd.

--mode full       inline includes; rewrite /assets and img/ to the live site
--mode worksheet  same, then blank executable code (keep comments) and $$ math
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_SITE = "https://ychsu987.github.io"
INCLUDE_RE = re.compile(r"\{\{<\s*include\s+([^\s>]+)\s*>\}\}")
FENCE_OPEN_RE = re.compile(r"^```")
EXECUTABLE_LANGS = {"r", "python", "python3", "webr", "dot"}
DISPLAY_MATH_RE = re.compile(r"\$\$.*?\$\$", re.S)
MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)(\{[^}]*\})?")
GENERATED_MARK = "Generated by scripts/flatten_qmd.py"

BLANKABLE_FENCE_RE = re.compile(
    r"^```\{(?P<lang>r|python|python3|webr|dot)(?P<opts>[^\n]*)\}\n"
    r"(?P<body>.*?)^```",
    re.M | re.S | re.I,
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def strip_quotes(value: str) -> str:
    return value.strip().strip('"').strip("'")


def strip_included_yaml(body: str) -> str:
    if not body.startswith("---"):
        return body
    parts = re.split(r"^---\s*$", body, maxsplit=2, flags=re.M)
    if len(parts) >= 3:
        return parts[2].lstrip("\n")
    return body


def resolve_include(raw: str, src: Path, root: Path) -> Path:
    raw = strip_quotes(raw)
    if raw.startswith("/"):
        return (root / raw.lstrip("/")).resolve()
    return (src.parent / raw).resolve()


def expand_includes(text: str, src: Path, root: Path, seen: set[Path] | None = None) -> str:
    seen = seen or set()
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    in_fence = False
    for line in lines:
        if FENCE_OPEN_RE.match(line.strip("\n")):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence or "{{<" not in line:
            out.append(line)
            continue

        def repl(match: re.Match[str]) -> str:
            path = resolve_include(match.group(1), src, root)
            if not path.is_file():
                raise FileNotFoundError(f"include not found: {path} (from {src})")
            if path in seen:
                raise RuntimeError(f"circular include: {path}")
            seen.add(path)
            body = strip_included_yaml(path.read_text(encoding="utf-8"))
            expanded = expand_includes(body, path, root, seen)
            seen.discard(path)
            return expanded.strip("\n") + "\n"

        out.append(INCLUDE_RE.sub(repl, line))
    return "".join(out)


def rewrite_assets_urls(text: str, site: str) -> str:
    text = re.sub(r"(?:\.\./)+assets/", f"{site}/assets/", text)
    return re.sub(rf"(?<!{re.escape(site)})/assets/", f"{site}/assets/", text)


def rewrite_markdown_images(text: str, lecture_dir: Path, root: Path, site: str) -> str:
    root = root.resolve()

    def repl(match: re.Match[str]) -> str:
        alt, target, attrs = match.group(1), match.group(2).strip(), match.group(3) or ""
        if re.match(r"https?://", target) or target.startswith("data:"):
            return match.group(0)
        if target.startswith("/"):
            return f"![{alt}]({site}{target}){attrs}"
        resolved = (lecture_dir / target).resolve()
        try:
            rel = resolved.relative_to(root).as_posix()
        except ValueError:
            return match.group(0)
        return f"![{alt}]({site}/{rel}){attrs}"

    return MD_IMAGE_RE.sub(repl, text)


def rewrite_quoted_local_files(text: str, lecture_dir: Path, root: Path, site: str) -> str:
    """Rewrite background-image='img/...' and similar quoted relative files."""
    root = root.resolve()
    pattern = re.compile(
        r"""((?:background-image|data-background)\s*[:=]\s*)(["'])([^"']+)\2"""
    )

    def repl(match: re.Match[str]) -> str:
        prefix, quote, target = match.group(1), match.group(2), match.group(3)
        if re.match(r"https?://", target) or target.startswith("data:"):
            return match.group(0)
        if target.startswith("/"):
            return f"{prefix}{quote}{site}{target}{quote}"
        if "img/" not in target.replace("\\", "/"):
            return match.group(0)
        resolved = (lecture_dir / target).resolve()
        try:
            rel = resolved.relative_to(root).as_posix()
        except ValueError:
            return match.group(0)
        return f"{prefix}{quote}{site}/{rel}{quote}"

    return pattern.sub(repl, text)


def rewrite_student_urls(text: str, lecture_path: Path, root: Path, site: str) -> str:
    lecture_dir = lecture_path.parent
    text = rewrite_assets_urls(text, site)
    text = rewrite_markdown_images(text, lecture_dir, root, site)
    text = rewrite_quoted_local_files(text, lecture_dir, root, site)
    return text


def blank_chunk(match: re.Match[str]) -> str:
    lang = match.group("lang")
    opts = match.group("opts")
    kept: list[str] = []
    for line in match.group("body").splitlines():
        stripped = line.strip()
        if stripped.startswith("#|") or stripped.startswith("//|"):
            kept.append(line)
            continue
        if stripped.startswith("#") or stripped.startswith("//"):
            kept.append(line)
    inner = "\n".join(kept)
    if inner:
        inner += "\n"
    else:
        inner = "\n"
    return f"```{{{lang}{opts}}}\n{inner}```"


def transform_outside_fences(text: str, fn) -> str:
    pieces: list[str] = []
    in_fence = False
    buf: list[str] = []
    for line in text.splitlines(keepends=True):
        if FENCE_OPEN_RE.match(line.strip("\n")):
            if in_fence:
                buf.append(line)
                pieces.append("".join(buf))
                buf = []
                in_fence = False
            else:
                if buf:
                    pieces.append(fn("".join(buf)))
                    buf = []
                buf.append(line)
                in_fence = True
            continue
        buf.append(line)
    if buf:
        pieces.append("".join(buf) if in_fence else fn("".join(buf)))
    return "".join(pieces)


def make_worksheet(text: str) -> str:
    text = BLANKABLE_FENCE_RE.sub(blank_chunk, text)
    return transform_outside_fences(text, lambda block: DISPLAY_MATH_RE.sub("$$\n\n$$\n", block))


def insert_generated_comment(text: str, source: Path, kind: str) -> str:
    comment = (
        f"<!-- {GENERATED_MARK} from {source.as_posix()} ({kind}). Do not edit by hand. -->\n"
    )
    if text.startswith("---"):
        parts = re.split(r"^---\s*$", text, maxsplit=2, flags=re.M)
        if len(parts) >= 3:
            yaml_body = parts[1]
            rest = parts[2].lstrip("\n")
            return f"---{yaml_body}---\n\n{comment}\n{rest}"
    return comment + "\n" + text


def output_path(source: Path, suffix: str, out_dir: Path | None) -> Path:
    name = f"{source.stem}-{suffix}.qmd"
    if out_dir is None:
        return source.with_name(name)
    out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir / name


def is_generated(path: Path) -> bool:
    if not path.is_file():
        return False
    head = path.read_text(encoding="utf-8")[:2000]
    return GENERATED_MARK in head


def should_skip(source: Path) -> bool:
    return is_generated(source)


def rel_to_root(path: Path, root: Path) -> Path:
    try:
        return path.relative_to(root)
    except ValueError:
        return path


def write_dest(dest: Path, text: str, root: Path, force: bool) -> bool:
    if dest.exists() and not is_generated(dest) and not force:
        print(
            f"refuse to overwrite source file: {rel_to_root(dest, root)}\n"
            f"  re-run with --out-dir student  or  --force",
            file=sys.stderr,
        )
        return False
    dest.write_text(text, encoding="utf-8")
    print(f"wrote {rel_to_root(dest, root)}")
    return True


def process_file(
    source: Path,
    root: Path,
    mode: str,
    site: str,
    out_dir: Path | None,
    force: bool,
) -> list[Path]:
    source = source.resolve()
    if should_skip(source):
        print(f"skip generated file: {rel_to_root(source, root)}", file=sys.stderr)
        return []
    original = source.read_text(encoding="utf-8")
    flat = expand_includes(original, source, root)
    flat = rewrite_student_urls(flat, source, root, site)
    written: list[Path] = []
    rel = rel_to_root(source, root)
    if out_dir is None:
        dest_dir = (root / "_student" / rel_to_root(source.parent, root)).resolve()
    elif out_dir.is_absolute():
        dest_dir = out_dir.resolve()
    else:
        dest_dir = (source.parent / out_dir).resolve()
    if mode in ("full", "both"):
        dest = output_path(source, "full", dest_dir)
        body = insert_generated_comment(flat, rel, "full")
        if write_dest(dest, body, root, force):
            written.append(dest)
    if mode in ("worksheet", "both"):
        dest = output_path(source, "worksheet", dest_dir)
        body = insert_generated_comment(make_worksheet(flat), rel, "worksheet")
        if write_dest(dest, body, root, force):
            written.append(dest)
    return written


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Flatten lecture .qmd files for student distribution."
    )
    parser.add_argument(
        "source",
        nargs="+",
        type=Path,
        help="Lecture .qmd with {{< include >}} shortcodes",
    )
    parser.add_argument(
        "--mode",
        choices=["full", "worksheet", "both"],
        default="full",
        help="full = flattened lecture; worksheet = blank student version; both = write both",
    )
    parser.add_argument(
        "--site",
        default=DEFAULT_SITE,
        help=f"Public site origin for /assets and img/ URLs (default: {DEFAULT_SITE})",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Directory for generated files (default: _student/<path-of-lecture>/, ignored by Quarto)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing file even if it is not a generated copy",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = repo_root()
    written = 0
    for src in args.source:
        path = src if src.is_absolute() else (Path.cwd() / src)
        if not path.is_file():
            print(f"not found: {src}", file=sys.stderr)
            return 1
        written += len(
            process_file(
                path,
                root,
                args.mode,
                args.site.rstrip("/"),
                args.out_dir,
                args.force,
            )
        )
    if written == 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
