#!/usr/bin/env python3
"""Build RStudio packs from BBMS1021 live-html tutorial wrappers.

Website tutorials stay live-html + {webr} with ::: {.hide} solutions.
This script writes standalone .qmd files that use {r} instead of {webr}:

  python scripts/pack_bbms1021_tutorials.py
  python scripts/pack_bbms1021_tutorials.py courses/2026/BBMS1021/tutorial_1.qmd

--mode worksheet  drop hide blocks (student RStudio worksheet)
--mode notes      unwrap hide blocks so answers are visible (teacher notes)
--mode both       write both (default)

Outputs go under _student/ (gitignored, not published).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import flatten_qmd as fq  # noqa: E402

GENERATED_MARK = "Generated by scripts/pack_bbms1021_tutorials.py"
DEFAULT_SOURCES = [
    "courses/2026/BBMS1021/tutorial_1.qmd",
    "courses/2026/BBMS1021/tutorial_2.qmd",
    "courses/2026/BBMS1021/tutorial_3.qmd",
]
FENCE_OPEN_RE = re.compile(r"^`{3,}")
DIV_OPEN_RE = re.compile(r"^(?P<colons>:{3,})\s*\{(?P<attrs>[^}]*)\}\s*$")
DIV_CLOSE_RE = re.compile(r"^(?P<colons>:{3,})\s*$")
WEBR_FENCE_RE = re.compile(r"^```\{webr(?P<opts>[^}]*)\}", re.M)
YAML_SPLIT_RE = re.compile(r"^---\s*$", re.M)


def split_yaml(text: str) -> tuple[str | None, str]:
    if not text.startswith("---"):
        return None, text
    parts = YAML_SPLIT_RE.split(text, maxsplit=2)
    if len(parts) >= 3:
        return parts[1], parts[2].lstrip("\n")
    return None, text


def pack_yaml(original_yaml: str | None, title_suffix: str | None) -> str:
    lines = [
        "title: \"Tutorial\"",
        "format:",
        "  html:",
        "    toc: true",
        "    toc-depth: 3",
        "    toc-location: left",
        "    self-contained: true",
        "engine: knitr",
        "eval: false",
        "lightbox: true",
        "author: \"Yu Cheng Hsu, BBMS1021 teaching team\"",
    ]
    title = "Tutorial"
    author = None
    date = None
    if original_yaml:
        for raw in original_yaml.splitlines():
            stripped = raw.strip()
            if stripped.startswith("title:"):
                title = stripped.split(":", 1)[1].strip().strip('"').strip("'")
            elif stripped.startswith("author:"):
                author = stripped.split(":", 1)[1].strip()
            elif stripped.startswith("date:"):
                date = stripped.split(":", 1)[1].strip()
    if title_suffix:
        title = f"{title} — {title_suffix}"
    lines[0] = f'title: "{title}"'
    if author:
        lines = [ln for ln in lines if not ln.startswith("author:")]
        lines.append(f"author: {author}")
    if date:
        lines.append(f"date: {date}")
    return "---\n" + "\n".join(lines) + "\n---\n"


def webr_to_r(text: str) -> str:
    return WEBR_FENCE_RE.sub(r"```{r\g<opts>}", text)


def is_hide_attrs(attrs: str) -> bool:
    token = attrs.strip()
    if token == ".hide" or token.startswith(".hide ") or token.startswith(".hide."):
        return True
    return bool(re.search(r"(^|[\s.])hide($|[\s.])", token))


def transform_hide_blocks(text: str, mode: str) -> str:
    """mode=worksheet removes hide blocks; mode=notes unwraps them."""
    out: list[str] = []
    hide_depth = 0
    div_stack: list[tuple[int, bool]] = []
    in_fence = False
    for line in text.splitlines(keepends=True):
        core = line.split("\n", 1)[0]
        stripped = core.strip()
        if FENCE_OPEN_RE.match(stripped):
            in_fence = not in_fence
            if hide_depth == 0 or mode == "notes":
                out.append(line)
            continue
        if in_fence:
            if hide_depth == 0 or mode == "notes":
                out.append(line)
            continue
        open_m = DIV_OPEN_RE.match(stripped)
        if open_m:
            n = len(open_m.group("colons"))
            hide = is_hide_attrs(open_m.group("attrs"))
            div_stack.append((n, hide))
            if hide:
                hide_depth += 1
                if mode == "notes":
                    continue
            if hide_depth == 0 or mode == "notes":
                out.append(line)
            continue
        close_m = DIV_CLOSE_RE.match(stripped)
        if close_m and div_stack:
            n = len(close_m.group("colons"))
            # close the nearest matching colon count, else the last open
            idx = next((i for i in range(len(div_stack) - 1, -1, -1) if div_stack[i][0] == n), len(div_stack) - 1)
            _n, was_hide = div_stack.pop(idx)
            if was_hide:
                hide_depth = max(0, hide_depth - 1)
                if mode == "notes":
                    continue
            if hide_depth == 0 or mode == "notes":
                out.append(line)
            continue
        if hide_depth == 0 or mode == "notes":
            out.append(line)
    return "".join(out)


def write_dest(dest: Path, text: str, root: Path, force: bool) -> bool:
    if dest.exists() and GENERATED_MARK not in dest.read_text(encoding="utf-8")[:2000] and not force:
        print(
            f"refuse to overwrite source file: {fq.rel_to_root(dest, root)}\n"
            f"  re-run with --out-dir  or  --force",
            file=sys.stderr,
        )
        return False
    dest.write_text(text, encoding="utf-8")
    print(f"wrote {fq.rel_to_root(dest, root)}")
    return True


def insert_comment(yaml_doc: str, body: str, source: Path, kind: str) -> str:
    comment = (
        f"<!--  -->\n"
    )
    return yaml_doc + "\n" + comment + "\n" + body.lstrip("\n")


def process_file(source: Path, root: Path, mode: str, dest_dir: Path, force: bool) -> list[Path]:
    original = source.read_text(encoding="utf-8")
    yaml_src, _ = split_yaml(original)
    flat = fq.expand_includes(original, source, root)
    _y, body = split_yaml(flat)
    body = webr_to_r(body)
    written: list[Path] = []
    jobs: list[tuple[str, str, str]] = []
    if mode in ("worksheet", "both"):
        jobs.append(("worksheet", "worksheet", "student worksheet"))
    if mode in ("notes", "both"):
        jobs.append(("notes", "notes", "teacher notes"))
    rel = fq.rel_to_root(source, root)
    for suffix, hide_mode, title_suffix in jobs:
        dest = dest_dir / f"{source.stem}-{suffix}.qmd"
        transformed = transform_hide_blocks(body, hide_mode)
        yaml_doc = pack_yaml(yaml_src, title_suffix)
        text = insert_comment(yaml_doc, transformed, rel, suffix)
        if write_dest(dest, text, root, force):
            written.append(dest)
    return written


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build BBMS1021 student worksheets and teacher notes (.qmd, {r} chunks)."
    )
    parser.add_argument(
        "source",
        nargs="*",
        type=Path,
        help="Website tutorial wrappers (default: 2026 BBMS1021 tutorial_1–3)",
    )
    parser.add_argument(
        "--mode",
        choices=["worksheet", "notes", "both"],
        default="both",
        help="worksheet = drop solutions; notes = show solutions; both = write both",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory (default: _student/<path-of-tutorial>/)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing file even if it is not a generated copy",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = fq.repo_root()
    sources = args.source or [Path(p) for p in DEFAULT_SOURCES]
    written = 0
    for src in sources:
        path = src if src.is_absolute() else (Path.cwd() / src)
        if not path.is_file():
            print(f"not found: {src}", file=sys.stderr)
            return 1
        rel = fq.rel_to_root(path.resolve(), root)
        if args.out_dir is None:
            dest_dir = (root / "_student" / rel.parent).resolve()
        elif args.out_dir.is_absolute():
            dest_dir = args.out_dir.resolve()
        else:
            dest_dir = (path.parent / args.out_dir).resolve()
        dest_dir.mkdir(parents=True, exist_ok=True)
        written += len(process_file(path.resolve(), root, args.mode, dest_dir, args.force))
    if written == 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
